# Generated by Django 2.2.16 on 2022-01-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220125_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для поста', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
